name: Adventure Build

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update Version
      shell: bash
      id: set-version
      run: |
          new_version=$(node ./.github/workflows/set-version.js ${{ github.ref }})
          echo "::add-mask::$new_version"
          echo $new_version
          echo "version=$new_version" >> "$GITHUB_OUTPUT"
    - run: zip -r ./module.zip module.json lang/ scripts/ images/ fonts/ packs/ styles/
    - name: Create Release
      id: create_versioned_release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        name: Release ${{ steps.set-version.outputs.version }}
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: './module.json,./module.zip'
